exp_name: "topologylora_qwen3_gsm8k"
model_id: "D:/code/model/Qwen3-1.7B" # 指向你的本地 Qwen3 模型路径
target_modules: 
  - "q_proj"
  - "k_proj"
  - "v_proj"
  - "o_proj"
  - "gate_proj"
  - "up_proj"
  - "down_proj"

# TopologyLoRA Allocator Params
max_rank: 64
min_rank: 4
beta: 2.5 
lora_alpha: 128
dropout: 0.05

# Optimization Params
batch_size: 2
grad_acc: 8
lr: 2e-4
epochs: 3
